global using Mapster;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using Todo.Service.Application.Models;
global using Todo.Service.Application.Services.Interfaces;
global using Todo.Service.Domain.Entities.General;
global using Todo.Service.Domain.Utils;
global using Todo.Service.Persistence;